### ISSUE TITLE
Problem with demo project

### ISSUE THREAD

**Issue by qed-** [khellang/Nancy.Swagger#55]
I'm attempting to run the demo project. If I run it (in Chrome) I see the following page at localhost:port/api-docs, rather than the Swagger UI:

```
{
swaggerVersion: "1.2",
  apis: [
  {
    path: "/users"
  }
]
}
```

Is there another URL I should be using?

Also note I had to add the following to Web.config to get the bootstrapper to run:
```
<nancyFx>
    <bootstrapper assembly="Nancy.Swagger.Demo" type="Nancy.Swagger.Demo.Bootstrapper" />
</nancyFx>
```

**Comment by khellang** [comment]
I can't see any images above. As I mentioned:

> This is correct behavior right now. **We don't include the swagger-ui as part of the package yet**

You have to pull in swagger-ui yourself. Using the `Nancy.Swagger` **won't** give you any UI right now.
